AWSTemplateFormatVersion: '2010-09-09'
Description: "Security Groups for Tier 3 Application"

Parameters:
  EnvironmentName:
    Type: String
    Description: "The environment name (dev or prod)"
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: "The ID of the VPC"

Resources:
  FrontendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${EnvironmentName} frontend security group"
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${EnvironmentName} backend security group"
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref FrontendSecurityGroup

Outputs:
  FrontendSecurityGroup:
    Value: !Ref FrontendSecurityGroup
  BackendSecurityGroup:
    Value: !Ref BackendSecurityGroup
