AWSTemplateFormatVersion: "2010-09-09"
Description: "ElastiCache Deploy in AWS"

Parameters:
  CacheNodeType:
    Description: "Tipo de nodo para ElastiCache"
    Type: String
    AllowedValues:
      - cache.t3.micro
      - cache.t3.small
      - cache.t3.medium
    Default: cache.t3.micro

  CacheEngine:
    Description: "Motor de ElastiCache"
    Type: String
    AllowedValues:
      - redis
      - memcached
    Default: redis

  PrivateSubnet3:
    Type: AWS::EC2::Subnet::Id
    Description: "ID de la tercera subred privada"

  PrivateSubnet4:
    Type: AWS::EC2::Subnet::Id
    Description: "ID de la cuarta subred privada"

Resources:
  ElastiCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: "Subredes para ElastiCache"
      SubnetIds:
        - !Ref PrivateSubnet3
        - !Ref PrivateSubnet4

  ElastiCacheCluster:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupDescription: "Cluster ElastiCache Multi-AZ"
      Engine: !Ref CacheEngine
      CacheNodeType: !Ref CacheNodeType
      NumCacheClusters: 2
      AutomaticFailoverEnabled: true
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup

Outputs:
  ElastiCacheClusterID:
    Description: "ID del cluster de ElastiCache"
    Value: !Ref ElastiCacheCluster
