AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS Secret in AWS"

Parameters:
  DBDescriptionParameter:
    Description: "Descripcion del secreto"
    Type: String

  DBNameParameter:
    Description: "Nombre del secreto"
    Type: String

  DBPasswordParameter:
    Description: "Contraseña del usuario maestro de la base de datos"
    NoEcho: true
    Type: String

  DBUserParameter:
    Description: "Nombre de usuario del usuario maestro de la base de datos"
    Type: String

  TagsParameter:
    Description: "Etiquetas para asociar el secreto a un proyecto"
    Type: String
    AllowedValues:
         - prd
         - test
         - dev
    Default: "prd"

Resources:
  SecretManagerDB:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Ref DBDescriptionParameter
      Name: !Ref DBNameParameter
      SecretString: !Sub
        '{"username": "${DBUserParameter}", "password": "${DBPasswordParameter}"}'
      Tags:
        - Key: Environment
          Value: !Ref TagsParameter
           
Outputs:
  SecretManagerDBArn:
    Description: "ARN del secreto almacenado en AWS Secrets Manager"
    Value: !Ref SecretManagerDB
  SecretManagerDBName:
    Description: "Nombre del secreto almacenado en AWS Secrets Manager"
    Value: !Ref SecretManagerDB
